# Generated by Django 2.2.1 on 2019-07-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190725_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='isFast',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vegetarianOptions',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
