# Generated by Django 2.2.1 on 2019-07-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_bookmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='isActive',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
