# Generated by Django 2.2.1 on 2019-07-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_restaurant_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='isActive',
            field=models.IntegerField(),
        ),
    ]
