# Generated by Django 2.2.1 on 2019-08-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='filters',
            name='title',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
