# Generated by Django 2.2.1 on 2019-08-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_filters_filter8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filters',
            name='filter1',
            field=models.CharField(default='f', max_length=5),
        ),
        migrations.AlterField(
            model_name='filters',
            name='filter2',
            field=models.CharField(default='f', max_length=5),
        ),
        migrations.AlterField(
            model_name='filters',
            name='filter3',
            field=models.CharField(default='f', max_length=5),
        ),
        migrations.AlterField(
            model_name='filters',
            name='filter4',
            field=models.CharField(default='f', max_length=5),
        ),
        migrations.AlterField(
            model_name='filters',
            name='filter5',
            field=models.CharField(default='f', max_length=5),
        ),
        migrations.AlterField(
            model_name='filters',
            name='filter6',
            field=models.CharField(default='f', max_length=5),
        ),
        migrations.AlterField(
            model_name='filters',
            name='filter7',
            field=models.CharField(default='f', max_length=5),
        ),
        migrations.AlterField(
            model_name='filters',
            name='filter8',
            field=models.CharField(default='f', max_length=5),
        ),
    ]
