# Generated by Django 2.2.1 on 2019-08-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190809_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='region',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
