# Generated by Django 2.2.1 on 2019-08-24 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_restaurant_other'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookModel',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='isCheap',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='other',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='isFast',
        ),
    ]
