# Generated by Django 2.2.1 on 2019-08-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190824_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
