# Generated by Django 2.2.1 on 2019-08-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190824_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filters',
            name='filter1',
        ),
        migrations.RemoveField(
            model_name='filters',
            name='filter2',
        ),
        migrations.RemoveField(
            model_name='filters',
            name='filter3',
        ),
        migrations.RemoveField(
            model_name='filters',
            name='filter4',
        ),
        migrations.RemoveField(
            model_name='filters',
            name='filter5',
        ),
        migrations.RemoveField(
            model_name='filters',
            name='filter6',
        ),
        migrations.RemoveField(
            model_name='filters',
            name='filter7',
        ),
        migrations.RemoveField(
            model_name='filters',
            name='filter8',
        ),
        migrations.AddField(
            model_name='filters',
            name='restaurantInfo',
            field=models.TextField(default='0'),
        ),
    ]
