# Generated by Django 2.2.1 on 2019-08-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190824_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='filters',
            name='filterInfo',
            field=models.TextField(default='0'),
        ),
    ]
