# Generated by Django 2.2.1 on 2019-08-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_filters_filterinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='usernamesVoted',
            field=models.TextField(default=''),
        ),
    ]
