# Generated by Django 2.2.1 on 2019-08-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_restaurant_usernamesvoted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='usernamesVoted',
            new_name='usernamesVotedUp',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='usernamesVotedDown',
            field=models.TextField(default=''),
        ),
    ]
