# Generated by Django 2.2.1 on 2019-08-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190825_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filters',
            old_name='filtersUsernamesVotedDown',
            new_name='filterUsernamesVotedDown',
        ),
    ]
