# Generated by Django 2.2.1 on 2020-04-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200423_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='usernamesVotedDown',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='usernamesVotedUp',
            field=models.TextField(default='', null=True),
        ),
    ]
