# Generated by Django 2.2.1 on 2020-04-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200425_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='usernamesVotedDown',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='usernamesVotedUp',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
